version: "3"

services:
  app:
    container_name: schedula_alerta
    image: schedula/alerta
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    volumes:
      - ".:/code/"
    ports:
      - "3005:3000"
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - NODE_ENV=DEVELOPMENT
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_DB=schedula_alerta
      - DATABASE_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: schedula_alerta_db
    ports:
      - "5106:5432"
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=schedula_alerta

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "schedula@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "schedula123!"
    ports:
      - "16546:80"
    depends_on:
      - postgres